# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelGenerator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modelGenerator.proto',
  package='ModelGenerator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14modelGenerator.proto\x12\x0eModelGenerator\"\x1e\n\x0cImageRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"O\n\x12LoadDatasetRequest\x12\x13\n\x0b\x64\x61tasetName\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61tasetType\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\x0c\"x\n\x11TrainModelRequest\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x16\n\x0etrainingEpochs\x18\x02 \x01(\x05\x12\x12\n\nlatentSize\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x61tasetName\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x05 \x01(\x0c\"%\n\x10LoadModelRequest\x12\x11\n\tmodelName\x18\x01 \x01(\t\"=\n\rImageResponse\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\"9\n\x13LoadDatasetResponse\x12\x11\n\tsuccesful\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x12TrainModelResponse\x12\x11\n\tsuccesful\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x11LoadModelResponse\x12\x11\n\tsuccesful\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xde\x02\n\x0fModelGeneration\x12L\n\rGenerateImage\x12\x1c.ModelGenerator.ImageRequest\x1a\x1d.ModelGenerator.ImageResponse\x12V\n\x0bLoadDataset\x12\".ModelGenerator.LoadDatasetRequest\x1a#.ModelGenerator.LoadDatasetResponse\x12S\n\nTrainModel\x12!.ModelGenerator.TrainModelRequest\x1a\".ModelGenerator.TrainModelResponse\x12P\n\tLoadModel\x12 .ModelGenerator.LoadModelRequest\x1a!.ModelGenerator.LoadModelResponseb\x06proto3'
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='ModelGenerator.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='ModelGenerator.ImageRequest.vector', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=70,
)


_LOADDATASETREQUEST = _descriptor.Descriptor(
  name='LoadDatasetRequest',
  full_name='ModelGenerator.LoadDatasetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetName', full_name='ModelGenerator.LoadDatasetRequest.datasetName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datasetType', full_name='ModelGenerator.LoadDatasetRequest.datasetType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='ModelGenerator.LoadDatasetRequest.dataset', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=151,
)


_TRAINMODELREQUEST = _descriptor.Descriptor(
  name='TrainModelRequest',
  full_name='ModelGenerator.TrainModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelName', full_name='ModelGenerator.TrainModelRequest.modelName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trainingEpochs', full_name='ModelGenerator.TrainModelRequest.trainingEpochs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latentSize', full_name='ModelGenerator.TrainModelRequest.latentSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datasetName', full_name='ModelGenerator.TrainModelRequest.datasetName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='ModelGenerator.TrainModelRequest.dataset', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=273,
)


_LOADMODELREQUEST = _descriptor.Descriptor(
  name='LoadModelRequest',
  full_name='ModelGenerator.LoadModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelName', full_name='ModelGenerator.LoadModelRequest.modelName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=312,
)


_IMAGERESPONSE = _descriptor.Descriptor(
  name='ImageResponse',
  full_name='ModelGenerator.ImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ModelGenerator.ImageResponse.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ModelGenerator.ImageResponse.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='ModelGenerator.ImageResponse.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=375,
)


_LOADDATASETRESPONSE = _descriptor.Descriptor(
  name='LoadDatasetResponse',
  full_name='ModelGenerator.LoadDatasetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succesful', full_name='ModelGenerator.LoadDatasetResponse.succesful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ModelGenerator.LoadDatasetResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=434,
)


_TRAINMODELRESPONSE = _descriptor.Descriptor(
  name='TrainModelResponse',
  full_name='ModelGenerator.TrainModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succesful', full_name='ModelGenerator.TrainModelResponse.succesful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ModelGenerator.TrainModelResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=492,
)


_LOADMODELRESPONSE = _descriptor.Descriptor(
  name='LoadModelResponse',
  full_name='ModelGenerator.LoadModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succesful', full_name='ModelGenerator.LoadModelResponse.succesful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ModelGenerator.LoadModelResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=549,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['LoadDatasetRequest'] = _LOADDATASETREQUEST
DESCRIPTOR.message_types_by_name['TrainModelRequest'] = _TRAINMODELREQUEST
DESCRIPTOR.message_types_by_name['LoadModelRequest'] = _LOADMODELREQUEST
DESCRIPTOR.message_types_by_name['ImageResponse'] = _IMAGERESPONSE
DESCRIPTOR.message_types_by_name['LoadDatasetResponse'] = _LOADDATASETRESPONSE
DESCRIPTOR.message_types_by_name['TrainModelResponse'] = _TRAINMODELRESPONSE
DESCRIPTOR.message_types_by_name['LoadModelResponse'] = _LOADMODELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

LoadDatasetRequest = _reflection.GeneratedProtocolMessageType('LoadDatasetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADDATASETREQUEST,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.LoadDatasetRequest)
  })
_sym_db.RegisterMessage(LoadDatasetRequest)

TrainModelRequest = _reflection.GeneratedProtocolMessageType('TrainModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINMODELREQUEST,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.TrainModelRequest)
  })
_sym_db.RegisterMessage(TrainModelRequest)

LoadModelRequest = _reflection.GeneratedProtocolMessageType('LoadModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADMODELREQUEST,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.LoadModelRequest)
  })
_sym_db.RegisterMessage(LoadModelRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

LoadDatasetResponse = _reflection.GeneratedProtocolMessageType('LoadDatasetResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADDATASETRESPONSE,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.LoadDatasetResponse)
  })
_sym_db.RegisterMessage(LoadDatasetResponse)

TrainModelResponse = _reflection.GeneratedProtocolMessageType('TrainModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINMODELRESPONSE,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.TrainModelResponse)
  })
_sym_db.RegisterMessage(TrainModelResponse)

LoadModelResponse = _reflection.GeneratedProtocolMessageType('LoadModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADMODELRESPONSE,
  '__module__' : 'modelGenerator_pb2'
  # @@protoc_insertion_point(class_scope:ModelGenerator.LoadModelResponse)
  })
_sym_db.RegisterMessage(LoadModelResponse)



_MODELGENERATION = _descriptor.ServiceDescriptor(
  name='ModelGeneration',
  full_name='ModelGenerator.ModelGeneration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=552,
  serialized_end=902,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateImage',
    full_name='ModelGenerator.ModelGeneration.GenerateImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadDataset',
    full_name='ModelGenerator.ModelGeneration.LoadDataset',
    index=1,
    containing_service=None,
    input_type=_LOADDATASETREQUEST,
    output_type=_LOADDATASETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainModel',
    full_name='ModelGenerator.ModelGeneration.TrainModel',
    index=2,
    containing_service=None,
    input_type=_TRAINMODELREQUEST,
    output_type=_TRAINMODELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadModel',
    full_name='ModelGenerator.ModelGeneration.LoadModel',
    index=3,
    containing_service=None,
    input_type=_LOADMODELREQUEST,
    output_type=_LOADMODELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELGENERATION)

DESCRIPTOR.services_by_name['ModelGeneration'] = _MODELGENERATION

# @@protoc_insertion_point(module_scope)
